export const HOME_STATUS_BATCH_SIZE = 5;
export const HOME_STATUS_TIMEOUT_MS = 8000;

export const ROUTE_DISPLAY_NAMES: Record<string, string> = {
  "36kr": "36氪",
  "51cto": "51CTO",
  "52pojie": "吾爱破解",
  acfun: "AcFun",
  baidu: "百度",
  bilibili: "哔哩哔哩",
  coolapk: "酷安",
  csdn: "CSDN",
  dgtle: "数字尾巴",
  douban: "豆瓣",
  "douban-group": "豆瓣讨论",
  "douban-movie": "豆瓣电影",
  douyin: "抖音",
  earthquake: "中国地震台",
  gameres: "GameRes 游资网",
  geekpark: "极客公园",
  genshin: "原神",
  github: "GitHub 趋势",
  guokr: "果壳",
  hackernews: "Hacker News",
  hellogithub: "HelloGitHub",
  history: "历史上的今天",
  honkai: "崩坏3",
  hostloc: "全球主机交流",
  hupu: "虎扑",
  huxiu: "虎嗅",
  ifanr: "爱范儿",
  ithome: "IT之家",
  "ithome-xijiayi": "IT之家喜加一",
  jianshu: "简书",
  juejin: "稀土掘金",
  kuaishou: "快手",
  linuxdo: "Linux DO",
  lol: "英雄联盟",
  miyoushe: "米游社",
  netease: "网易",
  "netease-news": "网易新闻",
  newsmth: "水木社区",
  ngabbs: "NGA",
  nodeseek: "NodeSeek",
  nytimes: "纽约时报",
  producthunt: "Product Hunt",
  "qq-news": "腾讯新闻",
  sina: "新浪",
  "sina-news": "新浪新闻",
  smzdm: "什么值得买",
  sspai: "少数派",
  starrail: "崩坏：星穹铁道",
  thepaper: "澎湃新闻",
  tieba: "百度贴吧",
  toutiao: "今日头条",
  v2ex: "V2EX",
  weatheralarm: "中央气象台预警",
  weibo: "微博",
  weread: "微信读书",
  yystv: "游研社",
  zhihu: "知乎",
  "zhihu-daily": "知乎日报",
};
